import type { Product, Category } from '@/types';

export const demoCategories: Category[] = [
  {
    id: 'cat-1',
    name_es: 'Equipos Médicos',
    name_en: 'Medical Equipment',
    slug: 'equipos-medicos',
    description_es: 'Equipos de diagnóstico y tratamiento',
    description_en: 'Diagnostic and treatment equipment',
    image_url: '',
  },
  {
    id: 'cat-2',
    name_es: 'Material Quirúrgico',
    name_en: 'Surgical Supplies',
    slug: 'material-quirurgico',
    description_es: 'Instrumental y material para cirugía',
    description_en: 'Instruments and supplies for surgery',
    image_url: '',
  },
  {
    id: 'cat-3',
    name_es: 'Insumos Médicos',
    name_en: 'Medical Supplies',
    slug: 'insumos-medicos',
    description_es: 'Consumibles y material desechable',
    description_en: 'Consumables and disposable materials',
    image_url: '',
  },
];

export const demoProducts: Product[] = [
  {
    id: 'prod-1',
    name_es: 'Monitor de Signos Vitales',
    name_en: 'Vital Signs Monitor',
    slug: 'monitor-signos-vitales',
    description_es: 'Monitor multiparámetro para medición de signos vitales. Pantalla LCD de alta resolución. Incluye sensores de SpO2, ECG, presión arterial y temperatura.',
    description_en: 'Multi-parameter monitor for vital signs measurement. High-resolution LCD screen. Includes SpO2, ECG, blood pressure and temperature sensors.',
    price_usd: 1250.00,
    price_bs: 45000.00,
    stock: 15,
    category_id: 'cat-1',
    images: ['/images/placeholder.svg'],
    featured: true,
    active: true,
    created_at: '2024-01-01',
  },
  {
    id: 'prod-2',
    name_es: 'Estetoscopio Littmann Classic III',
    name_en: 'Littmann Classic III Stethoscope',
    slug: 'estetoscopio-littmann-classic-iii',
    description_es: 'Estetoscopio de alto rendimiento con campana de doble cara. Ideal para profesionales de la salud.',
    description_en: 'High-performance stethoscope with dual-sided chest piece. Ideal for healthcare professionals.',
    price_usd: 120.00,
    price_bs: 4320.00,
    stock: 50,
    category_id: 'cat-1',
    images: ['/images/placeholder.svg'],
    featured: true,
    active: true,
    created_at: '2024-01-02',
  },
  {
    id: 'prod-3',
    name_es: 'Kit de Sutura Quirúrgica',
    name_en: 'Surgical Suture Kit',
    slug: 'kit-sutura-quirurgica',
    description_es: 'Kit completo de sutura con diferentes tipos de hilos y agujas. Material esterilizado y de alta calidad.',
    description_en: 'Complete suture kit with different types of threads and needles. Sterilized and high-quality material.',
    price_usd: 85.00,
    price_bs: 3060.00,
    stock: 100,
    category_id: 'cat-2',
    images: ['/images/placeholder.svg'],
    featured: false,
    active: true,
    created_at: '2024-01-03',
  },
  {
    id: 'prod-4',
    name_es: 'Guantes de Nitrilo (Caja x100)',
    name_en: 'Nitrile Gloves (Box x100)',
    slug: 'guantes-nitrilo-caja',
    description_es: 'Guantes de nitrilo sin polvo, alta resistencia. Caja de 100 unidades. Tallas S, M, L disponibles.',
    description_en: 'Powder-free nitrile gloves, high resistance. Box of 100 units. Sizes S, M, L available.',
    price_usd: 18.00,
    price_bs: 648.00,
    stock: 500,
    category_id: 'cat-3',
    images: ['/images/placeholder.svg'],
    featured: false,
    active: true,
    created_at: '2024-01-04',
  },
  {
    id: 'prod-5',
    name_es: 'Tensiómetro Digital de Brazo',
    name_en: 'Digital Arm Blood Pressure Monitor',
    slug: 'tensiometro-digital-brazo',
    description_es: 'Tensiómetro digital automático con pantalla grande. Memoria para 60 mediciones. Incluye brazalete universal.',
    description_en: 'Automatic digital blood pressure monitor with large display. Memory for 60 readings. Includes universal cuff.',
    price_usd: 45.00,
    price_bs: 1620.00,
    stock: 80,
    category_id: 'cat-1',
    images: ['/images/placeholder.svg'],
    featured: true,
    active: true,
    created_at: '2024-01-05',
  },
  {
    id: 'prod-6',
    name_es: 'Oxímetro de Pulso',
    name_en: 'Pulse Oximeter',
    slug: 'oximetro-pulso',
    description_es: 'Oxímetro de pulso de dedo con pantalla LED. Medición precisa de SpO2 y frecuencia cardíaca.',
    description_en: 'Finger pulse oximeter with LED display. Accurate SpO2 and heart rate measurement.',
    price_usd: 28.00,
    price_bs: 1008.00,
    stock: 120,
    category_id: 'cat-1',
    images: ['/images/placeholder.svg'],
    featured: false,
    active: true,
    created_at: '2024-01-06',
  },
  {
    id: 'prod-7',
    name_es: 'Pinzas Hemostáticas Kelly',
    name_en: 'Kelly Hemostatic Forceps',
    slug: 'pinzas-hemostaticas-kelly',
    description_es: 'Pinzas hemostáticas Kelly de acero inoxidable quirúrgico. 14cm de largo.',
    description_en: 'Kelly hemostatic forceps made of surgical stainless steel. 14cm long.',
    price_usd: 32.00,
    price_bs: 1152.00,
    stock: 60,
    category_id: 'cat-2',
    images: ['/images/placeholder.svg'],
    featured: false,
    active: true,
    created_at: '2024-01-07',
  },
  {
    id: 'prod-8',
    name_es: 'Mascarillas N95 (Caja x20)',
    name_en: 'N95 Masks (Box x20)',
    slug: 'mascarillas-n95-caja',
    description_es: 'Mascarillas respiratorias N95 certificadas. Alta filtración de partículas. Caja de 20 unidades.',
    description_en: 'Certified N95 respiratory masks. High particle filtration. Box of 20 units.',
    price_usd: 25.00,
    price_bs: 900.00,
    stock: 200,
    category_id: 'cat-3',
    images: ['/images/placeholder.svg'],
    featured: false,
    active: true,
    created_at: '2024-01-08',
  },
];
