import type { Product, Category } from '@/types';

// =====================================================
// 8 PRODUCT LINES from Brandbook (green → blue → navy)
// =====================================================
export const demoCategories: Category[] = [
  {
    id: 'cat-1',
    name_es: 'Equipos Médicos',
    name_en: 'Medical Equipment',
    slug: 'equipos-medicos',
    description_es: 'Monitores de signos vitales, desfibriladores, equipos de diagnóstico',
    description_en: 'Vital signs monitors, defibrillators, diagnostic equipment',
    image_url: '',
    color: '#7AB648',
  },
  {
    id: 'cat-2',
    name_es: 'Material Médico Quirúrgico',
    name_en: 'Surgical Supplies',
    slug: 'material-quirurgico',
    description_es: 'Guantes, batas, mallas, suturas, trocars, lencería quirúrgica',
    description_en: 'Gloves, gowns, meshes, sutures, trocars, surgical drapes',
    image_url: '',
    color: '#8BC66A',
  },
  {
    id: 'cat-3',
    name_es: 'Medias Antiembólicas',
    name_en: 'Anti-Embolism Stockings',
    slug: 'medias-antiembolicas',
    description_es: 'Compresión graduada para prevención de trombosis: rodilla, muslo y cadera',
    description_en: 'Graduated compression for thrombosis prevention: knee, thigh and hip',
    image_url: '',
    color: '#5BB5A2',
  },
  {
    id: 'cat-4',
    name_es: 'Cirugía Plástica y Post-quirúrgico',
    name_en: 'Plastic Surgery & Post-Op',
    slug: 'cirugia-plastica',
    description_es: 'Fajas, brassieres y prendas de compresión post-operatoria con hilado de cobre',
    description_en: 'Girdles, bras and post-operative compression garments with copper yarn',
    image_url: '',
    color: '#5BA8BF',
  },
  {
    id: 'cat-5',
    name_es: 'Órtesis y Rehabilitación',
    name_en: 'Orthosis & Rehabilitation',
    slug: 'ortesis-rehabilitacion',
    description_es: 'Muñequeras, coderas, rodilleras, inmovilizadores, collarines',
    description_en: 'Wrist braces, elbow supports, knee braces, immobilizers, cervical collars',
    image_url: '',
    color: '#6B8EC2',
  },
  {
    id: 'cat-6',
    name_es: 'Desinfección y Limpieza',
    name_en: 'Disinfection & Cleaning',
    slug: 'desinfeccion-limpieza',
    description_es: 'Soluciones antisépticas, jabones quirúrgicos, desinfectantes de alto nivel',
    description_en: 'Antiseptic solutions, surgical soaps, high-level disinfectants',
    image_url: '',
    color: '#5A6FAF',
  },
  {
    id: 'cat-7',
    name_es: 'Gases Medicinales',
    name_en: 'Medical Gases',
    slug: 'gases-medicinales',
    description_es: 'Sistemas de gases medicinales, vacío quirúrgico, instalaciones hospitalarias',
    description_en: 'Medical gas systems, surgical vacuum, hospital installations',
    image_url: '',
    color: '#3D4F8F',
  },
  {
    id: 'cat-8',
    name_es: 'Cuidado de Heridas',
    name_en: 'Wound Care',
    slug: 'cuidado-heridas',
    description_es: 'Apósitos, vendajes, material de curación, papeles de esterilización',
    description_en: 'Dressings, bandages, wound care materials, sterilization papers',
    image_url: '',
    color: '#0B1D4F',
  },
];

// =====================================================
// REAL PRODUCTS from Catálogo AltusPoint C.A.
// =====================================================
export const demoProducts: Product[] = [
  // ────────────────────────────────────────────
  // CAT-1: EQUIPOS MÉDICOS
  // ────────────────────────────────────────────
  {
    id: 'prod-1',
    name_es: 'Monitor de Signos Vitales Omni II',
    name_en: 'Omni II Vital Signs Monitor',
    slug: 'monitor-signos-vitales-omni-ii',
    description_es: 'Monitor multiparámetro con pantalla táctil para medición de signos vitales. Incluye sensores de SpO2, ECG, presión arterial no invasiva y temperatura. Pantalla LCD de alta resolución. Ideal para uso hospitalario y clínico.',
    description_en: 'Multi-parameter touchscreen monitor for vital signs measurement. Includes SpO2, ECG, non-invasive blood pressure and temperature sensors. High-resolution LCD display. Ideal for hospital and clinical use.',
    price_usd: 1250.00,
    price_bs: 45000.00,
    stock: 15,
    category_id: 'cat-1',
    images: ['/images/products/monitor-omni-ii.jpeg'],
    featured: true,
    active: true,
    created_at: '2025-01-01',
    brand: 'Infinium Medical',
    sku: 'INF-OMNI2',
    tags: ['monitor', 'signos-vitales', 'pantalla-tactil'],
  },

  // ────────────────────────────────────────────
  // CAT-2: MATERIAL MÉDICO QUIRÚRGICO
  // ────────────────────────────────────────────
  {
    id: 'prod-2',
    name_es: 'Guantes Estériles Gammex Non-Latex',
    name_en: 'Gammex Non-Latex Sterile Gloves',
    slug: 'guantes-esteriles-gammex-non-latex',
    description_es: 'Guantes quirúrgicos estériles sin látex de alta calidad. Libre de polvo, excelente sensibilidad táctil y resistencia. Ideales para cirugías y procedimientos donde se requiere máxima protección.',
    description_en: 'High-quality latex-free sterile surgical gloves. Powder-free, excellent tactile sensitivity and resistance. Ideal for surgeries and procedures requiring maximum protection.',
    price_usd: 22.00,
    price_bs: 792.00,
    stock: 300,
    category_id: 'cat-2',
    images: ['/images/products/guantes-gammex.png'],
    featured: false,
    active: true,
    created_at: '2025-01-02',
    brand: 'Ansell',
    sku: 'ANS-GMNL',
    tags: ['guantes', 'esteril', 'sin-latex'],
  },
  {
    id: 'prod-3',
    name_es: 'Bata Estéril Quirúrgica Alta Protección',
    name_en: 'High Protection Sterile Surgical Gown',
    slug: 'bata-esteril-quirurgica-alta-proteccion',
    description_es: 'Bata estéril para cirujano con máxima protección. Material de barrera avanzado que protege contra fluidos y agentes infecciosos. Confección ergonómica para comodidad durante procedimientos prolongados.',
    description_en: 'Sterile surgical gown with maximum protection. Advanced barrier material that protects against fluids and infectious agents. Ergonomic construction for comfort during prolonged procedures.',
    price_usd: 35.00,
    price_bs: 1260.00,
    stock: 150,
    category_id: 'cat-2',
    images: ['/images/products/bata-quirurgica.png'],
    featured: false,
    active: true,
    created_at: '2025-01-03',
    brand: 'Mölnlycke',
    sku: 'MOL-BATA-AP',
    tags: ['bata', 'esteril', 'alta-proteccion'],
  },
  {
    id: 'prod-4',
    name_es: 'Malla de Prolene para Hernia',
    name_en: 'Prolene Hernia Mesh',
    slug: 'malla-prolene-hernia',
    description_es: 'Malla quirúrgica de polipropileno para reparación de hernias. Material biocompatible, resistente y flexible. Disponible en varios tamaños para diferentes aplicaciones quirúrgicas.',
    description_en: 'Polypropylene surgical mesh for hernia repair. Biocompatible, resistant and flexible material. Available in various sizes for different surgical applications.',
    price_usd: 95.00,
    price_bs: 3420.00,
    stock: 80,
    category_id: 'cat-2',
    images: ['/images/products/malla-prolene.png'],
    featured: false,
    active: true,
    created_at: '2025-01-04',
    brand: 'Ethicon',
    sku: 'ETH-PROL-M',
    tags: ['malla', 'hernia', 'prolene'],
  },
  {
    id: 'prod-5',
    name_es: 'Engrapadora Quirúrgica Lineal',
    name_en: 'Linear Surgical Stapler',
    slug: 'engrapadora-quirurgica-lineal',
    description_es: 'Engrapadora quirúrgica lineal para procedimientos de resección y anastomosis. Diseño ergonómico con mecanismo de disparo suave. Grapas de titanio de alta calidad para una hemostasia segura.',
    description_en: 'Linear surgical stapler for resection and anastomosis procedures. Ergonomic design with smooth firing mechanism. High-quality titanium staples for secure hemostasis.',
    price_usd: 185.00,
    price_bs: 6660.00,
    stock: 40,
    category_id: 'cat-2',
    images: ['/images/products/engrapadora-quirurgica.png'],
    featured: true,
    active: true,
    created_at: '2025-01-05',
    brand: 'Ethicon',
    sku: 'ETH-STAP-L',
    tags: ['engrapadora', 'cirugia', 'lineal'],
  },
  {
    id: 'prod-6',
    name_es: 'Trocar Laparoscópico 12mm',
    name_en: '12mm Laparoscopic Trocar',
    slug: 'trocar-laparoscopico-12mm',
    description_es: 'Trocar para cirugía laparoscópica de 12mm. Diseño con válvula universal para minimizar la fuga de gas. Punta con sistema de seguridad para reducir el riesgo de lesiones.',
    description_en: '12mm trocar for laparoscopic surgery. Universal valve design to minimize gas leakage. Tip with safety system to reduce the risk of injuries.',
    price_usd: 68.00,
    price_bs: 2448.00,
    stock: 60,
    category_id: 'cat-2',
    images: ['/images/products/trocar-laparoscopico.png'],
    featured: false,
    active: true,
    created_at: '2025-01-06',
    brand: 'Ethicon',
    sku: 'ETH-TROC-12',
    tags: ['trocar', 'laparoscopia', '12mm'],
  },
  {
    id: 'prod-7',
    name_es: 'Kit de Lencería Quirúrgica de Bioseguridad',
    name_en: 'Surgical Biosafety Drape Kit',
    slug: 'kit-lenceria-quirurgica-bioseguridad',
    description_es: 'Kit completo de bioseguridad quirúrgica con productos de alta calidad que brindan protección al equipo quirúrgico en cirugías de alto riesgo. Incluye campos, compresas y sábanas estériles.',
    description_en: 'Complete surgical biosafety kit with high-quality products that provide protection to the surgical team in high-risk surgeries. Includes drapes, pads and sterile sheets.',
    price_usd: 48.00,
    price_bs: 1728.00,
    stock: 100,
    category_id: 'cat-2',
    images: ['/images/products/kit-lenceria-quirurgica.jpeg'],
    featured: false,
    active: true,
    created_at: '2025-01-07',
    brand: 'AltusPoint',
    sku: 'AP-KIT-BIO',
    tags: ['lenceria', 'bioseguridad', 'kit'],
  },

  // ────────────────────────────────────────────
  // CAT-3: MEDIAS ANTIEMBÓLICAS
  // ────────────────────────────────────────────
  {
    id: 'prod-8',
    name_es: 'Medias Antiembólicas Rodilla 18-23mmHg',
    name_en: 'Knee Anti-Embolism Stockings 18-23mmHg',
    slug: 'medias-antiembolicas-rodilla-18-23mmhg',
    description_es: 'Medias antiembólicas de compresión graduada decreciente 18-23mmHg. Banda elástica delicada autoajustable, protección antibacteriana de larga duración, orificio de inspección para evaluación médica. 80% Poliamida, 20% Elastano.',
    description_en: 'Anti-embolism stockings with graduated decreasing compression 18-23mmHg. Delicate self-adjusting elastic band, long-lasting antibacterial protection, inspection hole for medical evaluation. 80% Polyamide, 20% Elastane.',
    price_usd: 14.00,
    price_bs: 504.00,
    stock: 200,
    category_id: 'cat-3',
    images: ['/images/products/medias-antiembolicas-rodilla.png'],
    featured: true,
    active: true,
    created_at: '2025-01-08',
    brand: 'Medivaric',
    sku: '4463p',
    tags: ['medias', 'antiembolicas', 'rodilla', '18-23mmHg'],
  },
  {
    id: 'prod-9',
    name_es: 'Medias Antiembólicas Muslo 18-23mmHg',
    name_en: 'Thigh Anti-Embolism Stockings 18-23mmHg',
    slug: 'medias-antiembolicas-muslo-18-23mmhg',
    description_es: 'Medias antiembólicas hasta el muslo con compresión graduada 18-23mmHg. Ideales para postoperatorio y prevención de trombosis venosa profunda. Banda de silicona en el muslo para sujeción segura.',
    description_en: 'Thigh-high anti-embolism stockings with graduated compression 18-23mmHg. Ideal for post-operative and deep venous thrombosis prevention. Silicone band on thigh for secure hold.',
    price_usd: 18.00,
    price_bs: 648.00,
    stock: 150,
    category_id: 'cat-3',
    images: ['/images/products/medias-antiembolicas-muslo.png'],
    featured: false,
    active: true,
    created_at: '2025-01-09',
    brand: 'Medivaric',
    sku: 'MV-AE-MU',
    tags: ['medias', 'antiembolicas', 'muslo', '18-23mmHg'],
  },
  {
    id: 'prod-10',
    name_es: 'Medias Antiembólicas Cadera 18-23mmHg',
    name_en: 'Hip Anti-Embolism Stockings 18-23mmHg',
    slug: 'medias-antiembolicas-cadera-18-23mmhg',
    description_es: 'Medias antiembólicas hasta la cadera con compresión graduada 18-23mmHg. Máxima cobertura para pacientes encamados o con cirugías de cadera y miembros inferiores.',
    description_en: 'Hip-high anti-embolism stockings with graduated compression 18-23mmHg. Maximum coverage for bedridden patients or those with hip and lower limb surgeries.',
    price_usd: 22.00,
    price_bs: 792.00,
    stock: 100,
    category_id: 'cat-3',
    images: ['/images/products/medias-antiembolicas-cadera.png'],
    featured: false,
    active: true,
    created_at: '2025-01-10',
    brand: 'Medivaric',
    sku: 'MV-AE-CA',
    tags: ['medias', 'antiembolicas', 'cadera', '18-23mmHg'],
  },
  // Compression stockings
  {
    id: 'prod-11',
    name_es: 'Medias de Compresión Baja Rodilla 8-15mmHg Transparente',
    name_en: 'Low Compression Knee Stockings 8-15mmHg Transparent',
    slug: 'medias-compresion-baja-rodilla-8-15mmhg',
    description_es: 'Medias de compresión baja transparente hasta la rodilla. Compresión graduada 8-15mmHg, ideales para prevención diaria, viajes largos y piernas cansadas. Diseño estético y discreto.',
    description_en: 'Transparent low compression knee-high stockings. Graduated compression 8-15mmHg, ideal for daily prevention, long trips and tired legs. Aesthetic and discreet design.',
    price_usd: 12.00,
    price_bs: 432.00,
    stock: 250,
    category_id: 'cat-3',
    images: ['/images/products/medias-compresion-baja.png'],
    featured: false,
    active: true,
    created_at: '2025-01-11',
    brand: 'Medivaric',
    sku: 'MV-CB-ROD',
    tags: ['medias', 'compresion-baja', 'transparente', '8-15mmHg'],
  },
  {
    id: 'prod-12',
    name_es: 'Medias de Compresión Media Rodilla 15-20mmHg Transparente',
    name_en: 'Medium Compression Knee Stockings 15-20mmHg Transparent',
    slug: 'medias-compresion-media-rodilla-15-20mmhg',
    description_es: 'Medias terapéuticas de compresión media 15-20mmHg. Solución estética y terapéutica para insuficiencia venosa, várices y piernas cansadas. Costura plana y suave en la punta, plantilla de circulación. Certificación INVIMA, ISO y FDA.',
    description_en: 'Therapeutic medium compression stockings 15-20mmHg. Aesthetic and therapeutic solution for venous insufficiency, varicose veins and tired legs. Flat and soft seam at toe, circulation insole. INVIMA, ISO and FDA certified.',
    price_usd: 13.00,
    price_bs: 468.00,
    stock: 300,
    category_id: 'cat-3',
    images: ['/images/products/medias-compresion-media.png'],
    featured: true,
    active: true,
    created_at: '2025-01-12',
    brand: 'Medivaric',
    sku: '1123',
    tags: ['medias', 'compresion-media', 'transparente', '15-20mmHg'],
  },
  {
    id: 'prod-13',
    name_es: 'Medias de Compresión Alta Rodilla 20-30mmHg',
    name_en: 'High Compression Knee Stockings 20-30mmHg',
    slug: 'medias-compresion-alta-rodilla-20-30mmhg',
    description_es: 'Medias de compresión alta 20-30mmHg hasta la rodilla, opacas con dedos libres. Para tratamiento de insuficiencia venosa moderada a severa, post-escleroterapia y linfedema leve.',
    description_en: 'High compression stockings 20-30mmHg knee-high, opaque with open toe. For treatment of moderate to severe venous insufficiency, post-sclerotherapy and mild lymphedema.',
    price_usd: 16.00,
    price_bs: 576.00,
    stock: 120,
    category_id: 'cat-3',
    images: ['/images/products/medias-compresion-alta.png'],
    featured: false,
    active: true,
    created_at: '2025-01-13',
    brand: 'Medivaric',
    sku: 'MV-CA-ROD',
    tags: ['medias', 'compresion-alta', 'opaca', '20-30mmHg'],
  },
  {
    id: 'prod-14',
    name_es: 'Medias de Compresión Deportiva con Cobre 18-23mmHg',
    name_en: 'Copper Sport Compression Socks 18-23mmHg',
    slug: 'medias-compresion-deportiva-cobre',
    description_es: 'Medias de compresión deportiva con hilado de cobre 18-23mmHg. Propiedades antibacterianas, mejora la circulación y reduce la inflamación. Ideales para deportistas y personas activas.',
    description_en: 'Sport compression socks with copper yarn 18-23mmHg. Antibacterial properties, improves circulation and reduces inflammation. Ideal for athletes and active people.',
    price_usd: 15.00,
    price_bs: 540.00,
    stock: 180,
    category_id: 'cat-3',
    images: ['/images/products/medias-deportiva-cobre.png'],
    featured: false,
    active: true,
    created_at: '2025-01-14',
    brand: 'Medivaric',
    sku: 'MV-DEP-CU',
    tags: ['medias', 'deportiva', 'cobre', 'compresion'],
  },
  {
    id: 'prod-15',
    name_es: 'Calcetín Caballero Compresión Media 15-20mmHg',
    name_en: 'Men\'s Medium Compression Dress Socks 15-20mmHg',
    slug: 'calcetin-caballero-compresion-media',
    description_es: 'Calcetín de vestir para caballero con compresión graduada 15-20mmHg. Diseño de rombos elegante, ideal para uso diario en oficina. Mejora la circulación sin sacrificar el estilo.',
    description_en: 'Men\'s dress sock with graduated compression 15-20mmHg. Elegant diamond pattern design, ideal for daily office use. Improves circulation without sacrificing style.',
    price_usd: 14.00,
    price_bs: 504.00,
    stock: 200,
    category_id: 'cat-3',
    images: ['/images/products/calcetin-caballero.jpeg'],
    featured: false,
    active: true,
    created_at: '2025-01-15',
    brand: 'Medivaric',
    sku: 'MV-CAB-CM',
    tags: ['calcetin', 'caballero', 'compresion-media', 'vestir'],
  },
  {
    id: 'prod-16',
    name_es: 'Medias Viajero Travel Socks 15-20mmHg',
    name_en: 'Travel Socks 15-20mmHg',
    slug: 'medias-viajero-travel-socks',
    description_es: 'Medias de compresión unisex especialmente diseñadas para viajes largos. Compresión graduada 15-20mmHg que previene la hinchazón y fatiga de piernas durante vuelos y trayectos prolongados.',
    description_en: 'Unisex compression socks specially designed for long trips. Graduated compression 15-20mmHg that prevents swelling and leg fatigue during flights and long journeys.',
    price_usd: 14.00,
    price_bs: 504.00,
    stock: 150,
    category_id: 'cat-3',
    images: ['/images/products/medias-viajero.png'],
    featured: false,
    active: true,
    created_at: '2025-01-16',
    brand: 'Medivaric',
    sku: 'MV-TRAVEL',
    tags: ['medias', 'viajero', 'unisex', 'travel'],
  },
  {
    id: 'prod-17',
    name_es: 'Medias para Pie Diabético / Sensible',
    name_en: 'Diabetic / Sensitive Foot Socks',
    slug: 'medias-pie-diabetico-sensible',
    description_es: 'Medias unisex sin compresión para pie sensible y diabético. Sin costuras que irriten, tejido suave y transpirable. Protección y confort para pacientes con neuropatía periférica.',
    description_en: 'Unisex non-compression socks for sensitive and diabetic feet. Seamless design that won\'t irritate, soft and breathable fabric. Protection and comfort for patients with peripheral neuropathy.',
    price_usd: 10.00,
    price_bs: 360.00,
    stock: 200,
    category_id: 'cat-3',
    images: ['/images/products/medias-diabetico.png'],
    featured: false,
    active: true,
    created_at: '2025-01-17',
    brand: 'Medivaric',
    sku: 'MV-DIAB',
    tags: ['medias', 'diabetico', 'pie-sensible', 'sin-compresion'],
  },

  // ────────────────────────────────────────────
  // CAT-4: CIRUGÍA PLÁSTICA Y POST-QUIRÚRGICO
  // ────────────────────────────────────────────
  {
    id: 'prod-18',
    name_es: 'Faja Post-quirúrgica Ajustable con Hilado de Cobre',
    name_en: 'Adjustable Post-Surgical Girdle with Copper Yarn',
    slug: 'faja-postquirurgica-ajustable-cobre',
    description_es: 'Faja post-quirúrgica ajustable con hilado de cobre para procedimientos estéticos (liposucción, abdominoplastia, lipoláser). Sistema de cierre con 4 líneas de ganchos, moldeado glúteo preformado, cierre perineal con cremallera. Forro interno: 48% hilado de cobre, 46% poliamida, 6% elastano.',
    description_en: 'Adjustable post-surgical girdle with copper yarn for aesthetic procedures (liposuction, abdominoplasty, lipolaser). 4-hook closure system, pre-formed gluteal shaping, perineal zipper closure. Inner lining: 48% copper yarn, 46% polyamide, 6% elastane.',
    price_usd: 65.00,
    price_bs: 2340.00,
    stock: 50,
    category_id: 'cat-4',
    images: ['/images/products/faja-postquirurgica-ajustable.png'],
    featured: true,
    active: true,
    created_at: '2025-01-18',
    brand: 'Medivaric',
    sku: 'F126p',
    tags: ['faja', 'postquirurgica', 'cobre', 'liposuccion'],
  },
  {
    id: 'prod-19',
    name_es: 'Faja Post-quirúrgica Strapless con Cobre',
    name_en: 'Strapless Post-Surgical Girdle with Copper',
    slug: 'faja-postquirurgica-strapless-cobre',
    description_es: 'Faja post-quirúrgica sin tirantes con hilado de cobre. Diseño strapless ideal para procedimientos en el abdomen y espalda. Propiedades antibacterianas del cobre para una recuperación más rápida.',
    description_en: 'Strapless post-surgical girdle with copper yarn. Strapless design ideal for abdomen and back procedures. Antibacterial copper properties for faster recovery.',
    price_usd: 60.00,
    price_bs: 2160.00,
    stock: 40,
    category_id: 'cat-4',
    images: ['/images/products/faja-strapless.png'],
    featured: false,
    active: true,
    created_at: '2025-01-19',
    brand: 'Medivaric',
    sku: 'MV-FJ-STRAP',
    tags: ['faja', 'strapless', 'postquirurgica', 'cobre'],
  },
  {
    id: 'prod-20',
    name_es: 'Brassier Post-quirúrgico con Hilado de Cobre',
    name_en: 'Post-Surgical Bra with Copper Yarn',
    slug: 'brassier-postquirurgico-cobre',
    description_es: 'Brassier post-quirúrgico ajustable con hilado de cobre. Diseñado para recuperación después de cirugías de mama. Soporte firme pero cómodo con propiedades regenerativas del cobre.',
    description_en: 'Adjustable post-surgical bra with copper yarn. Designed for recovery after breast surgeries. Firm but comfortable support with regenerative copper properties.',
    price_usd: 45.00,
    price_bs: 1620.00,
    stock: 60,
    category_id: 'cat-4',
    images: ['/images/products/brassier-postquirurgico.png'],
    featured: false,
    active: true,
    created_at: '2025-01-20',
    brand: 'Medivaric',
    sku: 'MV-BRAS-CU',
    tags: ['brassier', 'postquirurgico', 'cobre', 'mama'],
  },
  {
    id: 'prod-21',
    name_es: 'Mentonera Post-quirúrgica con Cobre',
    name_en: 'Post-Surgical Chin Strap with Copper',
    slug: 'mentonera-postquirurgica-cobre',
    description_es: 'Mentonera de compresión con hilado de cobre para post-operatorio de cirugías faciales. Ideal para mentoplastia, liposucción de papada y lifting facial.',
    description_en: 'Compression chin strap with copper yarn for post-operative facial surgeries. Ideal for mentoplasty, chin liposuction and face lift.',
    price_usd: 28.00,
    price_bs: 1008.00,
    stock: 45,
    category_id: 'cat-4',
    images: ['/images/products/mentonera-postquirurgica.png'],
    featured: false,
    active: true,
    created_at: '2025-01-21',
    brand: 'Medivaric',
    sku: 'MV-MENT-CU',
    tags: ['mentonera', 'facial', 'postquirurgico', 'cobre'],
  },
  {
    id: 'prod-22',
    name_es: 'Tabla Post-quirúrgica MDF con Cobre',
    name_en: 'Post-Surgical MDF Board with Copper',
    slug: 'tabla-postquirurgica-mdf-cobre',
    description_es: 'Tabla post-quirúrgica de MDF con hilado de cobre para uso debajo de la faja. Ayuda a mantener la presión uniforme y previene fibrosis después de liposucción.',
    description_en: 'Post-surgical MDF board with copper yarn for use under the girdle. Helps maintain uniform pressure and prevents fibrosis after liposuction.',
    price_usd: 18.00,
    price_bs: 648.00,
    stock: 70,
    category_id: 'cat-4',
    images: ['/images/products/tabla-postquirurgica.png'],
    featured: false,
    active: true,
    created_at: '2025-01-22',
    brand: 'Medivaric',
    sku: 'MV-TABLA-CU',
    tags: ['tabla', 'postquirurgica', 'mdf', 'cobre'],
  },
  {
    id: 'prod-23',
    name_es: 'Short Materno Copper Mom',
    name_en: 'Copper Mom Maternity Short',
    slug: 'short-materno-copper-mom',
    description_es: 'Short de soporte materno con hilado de cobre de la línea Copper Mom. Soporte para vientre durante el embarazo, mejora circulación y reduce hinchazón. Propiedades antibacterianas naturales del cobre.',
    description_en: 'Maternity support short with copper yarn from the Copper Mom line. Belly support during pregnancy, improves circulation and reduces swelling. Natural antibacterial copper properties.',
    price_usd: 35.00,
    price_bs: 1260.00,
    stock: 40,
    category_id: 'cat-4',
    images: ['/images/products/short-materno.jpeg'],
    featured: false,
    active: true,
    created_at: '2025-01-23',
    brand: 'Medivaric',
    sku: 'MV-MAT-SHORT',
    tags: ['materno', 'embarazo', 'cobre', 'copper-mom'],
  },

  // ────────────────────────────────────────────
  // CAT-5: ÓRTESIS Y REHABILITACIÓN
  // ────────────────────────────────────────────
  {
    id: 'prod-24',
    name_es: 'Brace de Muñeca con Hilado de Cobre',
    name_en: 'Copper Yarn Wrist Brace',
    slug: 'brace-muneca-cobre',
    description_es: 'Muñequera con hilado de cobre para soporte y recuperación efectiva. Reduce inflamación y promueve circulación. Ideal para síndrome de túnel carpiano y lesiones de muñeca.',
    description_en: 'Copper yarn wrist brace for effective support and recovery. Reduces inflammation and promotes circulation. Ideal for carpal tunnel syndrome and wrist injuries.',
    price_usd: 16.00,
    price_bs: 576.00,
    stock: 80,
    category_id: 'cat-5',
    images: ['/images/products/brace-muneca.jpg'],
    featured: false,
    active: true,
    created_at: '2025-01-24',
    brand: 'Medivaric',
    sku: 'MV-ORT-MU',
    tags: ['muñequera', 'brace', 'cobre', 'tunel-carpiano'],
  },
  {
    id: 'prod-25',
    name_es: 'Soporte de Codo con Hilado de Cobre',
    name_en: 'Copper Yarn Elbow Support',
    slug: 'soporte-codo-cobre',
    description_es: 'Codera con hilado de cobre para alivio de dolor articular. Compresión suave que reduce la inflamación, ideal para codo de tenista y bursitis.',
    description_en: 'Copper yarn elbow support for joint pain relief. Gentle compression that reduces inflammation, ideal for tennis elbow and bursitis.',
    price_usd: 9.00,
    price_bs: 324.00,
    stock: 100,
    category_id: 'cat-5',
    images: ['/images/products/soporte-codo.jpg'],
    featured: false,
    active: true,
    created_at: '2025-01-25',
    brand: 'Medivaric',
    sku: 'MV-ORT-CO',
    tags: ['codera', 'cobre', 'codo-de-tenista'],
  },
  {
    id: 'prod-26',
    name_es: 'Estabilizador de Rodilla con Cobre',
    name_en: 'Copper Knee Stabilizer',
    slug: 'estabilizador-rodilla-cobre',
    description_es: 'Estabilizador de rodilla con hilado de cobre para máximo soporte lateral. Ideal para lesiones de ligamentos, rehabilitación post-operatoria y estabilidad durante actividades físicas.',
    description_en: 'Copper yarn knee stabilizer for maximum lateral support. Ideal for ligament injuries, post-operative rehabilitation and stability during physical activities.',
    price_usd: 24.00,
    price_bs: 864.00,
    stock: 70,
    category_id: 'cat-5',
    images: ['/images/products/estabilizador-rodilla.jpg'],
    featured: true,
    active: true,
    created_at: '2025-01-26',
    brand: 'Medivaric',
    sku: 'MV-ORT-ESTAB',
    tags: ['rodillera', 'estabilizador', 'cobre', 'rehabilitacion'],
  },
  {
    id: 'prod-27',
    name_es: 'Brace de Rodilla con Articulación Libre',
    name_en: 'Free-Joint Knee Brace',
    slug: 'brace-rodilla-articulacion-libre',
    description_es: 'Brace de rodilla con articulación libre y hilado de cobre. Permite rango de movimiento controlado para rehabilitación progresiva. Soportes laterales metálicos para estabilidad.',
    description_en: 'Knee brace with free joint and copper yarn. Allows controlled range of motion for progressive rehabilitation. Metal lateral supports for stability.',
    price_usd: 25.00,
    price_bs: 900.00,
    stock: 50,
    category_id: 'cat-5',
    images: ['/images/products/brace-rodilla.jpg'],
    featured: false,
    active: true,
    created_at: '2025-01-27',
    brand: 'Medivaric',
    sku: 'MV-ORT-BR-ART',
    tags: ['brace', 'rodilla', 'articulacion', 'cobre'],
  },
  {
    id: 'prod-28',
    name_es: 'Brace Postoperatorio para Rodilla',
    name_en: 'Postoperative Knee Brace',
    slug: 'brace-postoperatorio-rodilla',
    description_es: 'Brace post-operatorio de rodilla con sistema de bloqueo angular ajustable. Para rehabilitación después de cirugía de ligamento cruzado, menisco o reemplazo de rodilla.',
    description_en: 'Postoperative knee brace with adjustable angular locking system. For rehabilitation after cruciate ligament, meniscus or knee replacement surgery.',
    price_usd: 115.00,
    price_bs: 4140.00,
    stock: 25,
    category_id: 'cat-5',
    images: ['/images/products/brace-postoperatorio.jpg'],
    featured: false,
    active: true,
    created_at: '2025-01-28',
    brand: 'Medivaric',
    sku: 'MV-ORT-POST',
    tags: ['brace', 'postoperatorio', 'rodilla', 'rehabilitacion'],
  },
  {
    id: 'prod-29',
    name_es: 'Tobillera Estabilizadora con Cobre',
    name_en: 'Copper Ankle Stabilizer',
    slug: 'tobillera-estabilizadora-cobre',
    description_es: 'Estabilizador de tobillo con hilado de cobre. Soporte firme para esguinces, tendinitis y recuperación post-lesión. Propiedades antiinflamatorias del cobre.',
    description_en: 'Copper yarn ankle stabilizer. Firm support for sprains, tendonitis and post-injury recovery. Anti-inflammatory copper properties.',
    price_usd: 19.00,
    price_bs: 684.00,
    stock: 90,
    category_id: 'cat-5',
    images: ['/images/products/tobillera-estabilizadora.jpg'],
    featured: false,
    active: true,
    created_at: '2025-01-29',
    brand: 'Medivaric',
    sku: 'MV-ORT-TOB',
    tags: ['tobillera', 'estabilizador', 'cobre', 'esguince'],
  },
  {
    id: 'prod-30',
    name_es: 'Soporte para Fascitis Plantar con Gel',
    name_en: 'Plantar Fasciitis Support with Gel',
    slug: 'soporte-fascitis-plantar-gel',
    description_es: 'Soporte para fascitis plantar con almohadilla de gel y hilado de cobre. Alivio de dolor en el talón y arco del pie. Uso diario discreto dentro del calzado.',
    description_en: 'Plantar fasciitis support with gel pad and copper yarn. Relief for heel and arch pain. Discreet daily use inside footwear.',
    price_usd: 9.00,
    price_bs: 324.00,
    stock: 120,
    category_id: 'cat-5',
    images: ['/images/products/fascitis-plantar.jpg'],
    featured: false,
    active: true,
    created_at: '2025-01-30',
    brand: 'Medivaric',
    sku: 'MV-ORT-FP',
    tags: ['fascitis', 'plantar', 'gel', 'cobre'],
  },

  // ────────────────────────────────────────────
  // CAT-6: DESINFECCIÓN Y LIMPIEZA
  // ────────────────────────────────────────────
  {
    id: 'prod-31',
    name_es: 'Desinfectante de Superficies Exeol Floor',
    name_en: 'Exeol Floor Surface Disinfectant',
    slug: 'desinfectante-superficies-exeol-floor',
    description_es: 'Desinfectante ultraconcentrado de superficies para pisos y paredes hospitalarias. Fórmula francesa de alto rendimiento que combina eficacia, ecología y tecnicidad. Uso en áreas críticas.',
    description_en: 'Ultra-concentrated surface disinfectant for hospital floors and walls. French high-performance formula combining effectiveness, ecology and technicality. Use in critical areas.',
    price_usd: 42.00,
    price_bs: 1512.00,
    stock: 100,
    category_id: 'cat-6',
    images: ['/images/products/exeol-floor.png'],
    featured: false,
    active: true,
    created_at: '2025-02-01',
    brand: 'Exeol',
    sku: 'EX-FLOOR',
    tags: ['desinfectante', 'pisos', 'paredes', 'hospital'],
  },
  {
    id: 'prod-32',
    name_es: 'Jabón Multi-enzimático Exeol 4E',
    name_en: 'Exeol 4E Multi-enzymatic Soap',
    slug: 'jabon-multienzimatico-exeol-4e',
    description_es: 'Jabón multi-enzimático con 4 enzimas para limpieza de instrumental médico. Elimina eficazmente residuos orgánicos de instrumentos quirúrgicos antes de la esterilización.',
    description_en: 'Multi-enzymatic soap with 4 enzymes for medical instrument cleaning. Effectively removes organic residue from surgical instruments before sterilization.',
    price_usd: 38.00,
    price_bs: 1368.00,
    stock: 80,
    category_id: 'cat-6',
    images: ['/images/products/exeol-4e.png'],
    featured: false,
    active: true,
    created_at: '2025-02-02',
    brand: 'Exeol',
    sku: 'EX-4E',
    tags: ['jabon', 'multienzimatico', 'instrumental', 'limpieza'],
  },
  {
    id: 'prod-33',
    name_es: 'Detergente Desinfectante Exeol Surf Optimal',
    name_en: 'Exeol Surf Optimal Disinfectant Detergent',
    slug: 'detergente-desinfectante-exeol-surf-optimal',
    description_es: 'Detergente desinfectante sin alcohol para superficies, mobiliario y equipos médicos. Fórmula suave pero efectiva, no daña superficies delicadas. Ideal para limpieza diaria hospitalaria.',
    description_en: 'Alcohol-free disinfectant detergent for surfaces, furniture and medical equipment. Gentle but effective formula that does not damage delicate surfaces. Ideal for daily hospital cleaning.',
    price_usd: 36.00,
    price_bs: 1296.00,
    stock: 90,
    category_id: 'cat-6',
    images: ['/images/products/exeol-surf-optimal.png'],
    featured: false,
    active: true,
    created_at: '2025-02-03',
    brand: 'Exeol',
    sku: 'EX-SURF',
    tags: ['detergente', 'desinfectante', 'sin-alcohol', 'superficies'],
  },
  {
    id: 'prod-34',
    name_es: 'Glutaraldehído 2% – Desinfectante de Alto Nivel (GTA 2%)',
    name_en: '2% Glutaraldehyde – High-Level Disinfectant (GTA 2%)',
    slug: 'glutaraldehido-2-desinfectante-alto-nivel',
    description_es: 'Desinfectante de alto nivel a base de glutaraldehído al 2%. Ideal para sistemas de endoscopia, dispositivos médicos termosensibles e instrumental quirúrgico que no puede ser autoclavado.',
    description_en: '2% glutaraldehyde-based high-level disinfectant. Ideal for endoscopy systems, thermosensitive medical devices and surgical instruments that cannot be autoclaved.',
    price_usd: 55.00,
    price_bs: 1980.00,
    stock: 50,
    category_id: 'cat-6',
    images: ['/images/products/glutaraldehido-gta2.png'],
    featured: true,
    active: true,
    created_at: '2025-02-04',
    brand: 'Exeol',
    sku: 'EX-GTA2',
    tags: ['glutaraldehido', 'desinfectante', 'alto-nivel', 'endoscopia'],
  },
  {
    id: 'prod-35',
    name_es: 'Jabón Antiséptico con Clorhexidina al 4%',
    name_en: 'Antiseptic Soap with 4% Chlorhexidine',
    slug: 'jabon-antiseptico-clorhexidina-4',
    description_es: 'Jabón con gluconato de clorhexidina al 4% para lavado de manos quirúrgico. Amplio espectro antimicrobiano con efecto residual prolongado. Uso hospitalario profesional.',
    description_en: 'Soap with 4% chlorhexidine gluconate for surgical hand washing. Broad antimicrobial spectrum with prolonged residual effect. Professional hospital use.',
    price_usd: 18.00,
    price_bs: 648.00,
    stock: 120,
    category_id: 'cat-6',
    images: ['/images/products/clorhexidina-jabon.png'],
    featured: false,
    active: true,
    created_at: '2025-02-05',
    brand: 'Wescohex',
    sku: 'WQ-CHX4',
    tags: ['jabon', 'clorhexidina', 'antiseptico', 'quirurgico'],
  },

  // ────────────────────────────────────────────
  // CAT-7: GASES MEDICINALES
  // ────────────────────────────────────────────
  {
    id: 'prod-36',
    name_es: 'Proyecto de Sistema de Gases Medicinales (Consultar)',
    name_en: 'Medical Gas System Project (Inquire)',
    slug: 'proyecto-sistema-gases-medicinales',
    description_es: 'Elaboración de proyectos de Sistemas de Gases Medicinales, Vacío Médico Quirúrgico y WAGD bajo norma NFPA-99. Incluye suministro e instalación de tuberías, manifolds, válvulas, alarmas, tomas de gases medicinales de pared. Equipos OHIO Medical (fabricación americana).',
    description_en: 'Design of Medical Gas Systems, Surgical Medical Vacuum and WAGD projects under NFPA-99 standard. Includes supply and installation of piping, manifolds, valves, alarms, wall medical gas outlets. OHIO Medical equipment (American made).',
    price_usd: 0.00,
    price_bs: 0.00,
    stock: 999,
    category_id: 'cat-7',
    images: ['/images/products/ohio-medical-gases.png'],
    featured: true,
    active: true,
    created_at: '2025-02-06',
    brand: 'OHIO Medical',
    sku: 'OHIO-PROJ',
    tags: ['gases', 'medicinales', 'proyecto', 'NFPA-99', 'instalacion'],
  },

  // ────────────────────────────────────────────
  // CAT-8: CUIDADO DE HERIDAS
  // ────────────────────────────────────────────
  {
    id: 'prod-37',
    name_es: 'Apósitos para Ostomía Hollister',
    name_en: 'Hollister Ostomy Dressings',
    slug: 'apositos-ostomia-hollister',
    description_es: 'Productos para cuidado de ostomía marca Hollister. Sistema de barrera cutánea que protege la piel periestomal. Diseñados para máximo confort y seguridad del paciente ostomizado.',
    description_en: 'Hollister ostomy care products. Skin barrier system that protects peristomal skin. Designed for maximum comfort and safety of the ostomy patient.',
    price_usd: 28.00,
    price_bs: 1008.00,
    stock: 80,
    category_id: 'cat-8',
    images: ['/images/products/hollister-ostomy.jpeg'],
    featured: false,
    active: true,
    created_at: '2025-02-07',
    brand: 'Hollister',
    sku: 'HOL-OSTM',
    tags: ['ostomia', 'aposito', 'barrera-cutanea'],
  },
  {
    id: 'prod-38',
    name_es: 'Apósitos Cutimed para Cuidado de Heridas',
    name_en: 'Cutimed Wound Care Dressings',
    slug: 'apositos-cutimed-cuidado-heridas',
    description_es: 'Apósitos avanzados para cuidado de heridas marca ESSIT/Cutimed. Tecnología de absorción superior para manejo de heridas crónicas y agudas. Promueven un ambiente húmedo óptimo para la cicatrización.',
    description_en: 'Advanced wound care dressings by ESSIT/Cutimed. Superior absorption technology for chronic and acute wound management. Promote an optimal moist environment for healing.',
    price_usd: 22.00,
    price_bs: 792.00,
    stock: 100,
    category_id: 'cat-8',
    images: ['/images/products/cutimed-wound-care.png'],
    featured: false,
    active: true,
    created_at: '2025-02-08',
    brand: 'Cutimed/ESSIT',
    sku: 'CUT-WOUND',
    tags: ['aposito', 'heridas', 'cutimed', 'cicatrizacion'],
  },
  {
    id: 'prod-39',
    name_es: 'Apósito Estéril Leukomed T Plus Skin Sensitive',
    name_en: 'Leukomed T Plus Skin Sensitive Sterile Dressing',
    slug: 'aposito-esteril-leukomed-t-plus',
    description_es: 'Apósito estéril transparente con adhesivo suave para pieles sensibles. Permite monitoreo visual de la herida sin necesidad de retiro. Barrera impermeable contra bacterias y agua.',
    description_en: 'Sterile transparent dressing with gentle adhesive for sensitive skin. Allows visual wound monitoring without removal. Waterproof barrier against bacteria and water.',
    price_usd: 8.00,
    price_bs: 288.00,
    stock: 200,
    category_id: 'cat-8',
    images: ['/images/products/leukomed-aposito.png'],
    featured: false,
    active: true,
    created_at: '2025-02-09',
    brand: 'Leukoplast',
    sku: 'LEU-TPSS',
    tags: ['aposito', 'esteril', 'transparente', 'piel-sensible'],
  },
  {
    id: 'prod-40',
    name_es: 'Rollos de Papel para Esterilización (Vapor y Óxido de Etileno)',
    name_en: 'Sterilization Paper Rolls (Steam & Ethylene Oxide)',
    slug: 'rollos-papel-esterilizacion',
    description_es: 'Rollos de papel Pergut para esterilización por vapor y óxido de etileno. Material resistente que garantiza la esterilidad del instrumental empaquetado hasta su uso. Indicador de proceso incluido.',
    description_en: 'Pergut paper rolls for steam and ethylene oxide sterilization. Resistant material that guarantees sterility of packaged instruments until use. Process indicator included.',
    price_usd: 15.00,
    price_bs: 540.00,
    stock: 150,
    category_id: 'cat-8',
    images: ['/images/products/rollos-esterilizacion.png'],
    featured: false,
    active: true,
    created_at: '2025-02-10',
    brand: 'BolsaPlast Medical',
    sku: 'BPM-ROLL',
    tags: ['esterilizacion', 'papel', 'pergut', 'vapor'],
  },
];
